# Generated by Django 6.0.2 on 2026-03-11 18:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPageType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('description', models.TextField(blank=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_page_types', to='workspaces.workspace')),
            ],
            options={
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PropertyDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('page_type', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('prop_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('checkbox', 'Checkbox'), ('select', 'Select'), ('multi', 'Multi Select'), ('url', 'URL'), ('email', 'Email'), ('phone', 'Phone'), ('currency', 'Currency'), ('relation', 'Relation'), ('file', 'File'), ('object', 'Object')], max_length=50)),
                ('options', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
                ('is_global', models.BooleanField(default=False)),
                ('custom_page_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.custompagetype')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_definitions', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('value_text', models.TextField(blank=True)),
                ('value_number', models.FloatField(blank=True, null=True)),
                ('value_date', models.DateTimeField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.propertydefinition')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='pages.page')),
            ],
            options={
                'unique_together': {('page', 'definition')},
            },
        ),
    ]
