# Generated by Django 6.0.3 on 2026-03-23 00:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompagetype',
            name='is_pinned',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PageTypeGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#7c3aed', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_type_groups', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.AddField(
            model_name='custompagetype',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_types', to='properties.pagetypegroup'),
        ),
    ]
