# Generated by Django 6.0.3 on 2026-03-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_custompagetype_is_pinned_pagetypegroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custompagetype',
            name='default_color',
            field=models.CharField(blank=True, default='#7c3aed', max_length=20),
        ),
        migrations.AddField(
            model_name='custompagetype',
            name='default_icon',
            field=models.CharField(blank=True, default='📄', max_length=10),
        ),
    ]
