# Generated by Django 6.0.2 on 2026-03-11 18:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('enc_tier', models.CharField(choices=[('standard', 'Standard'), ('private', 'Private'), ('inherited', 'Inherited'), ('browser', 'Browser Encryption')], default='standard', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('enc_key_blob', models.TextField(blank=True)),
                ('enc_key_salt', models.CharField(blank=True, max_length=64)),
                ('enc_key_hint', models.CharField(blank=True, max_length=255)),
                ('enc_recovery_blob', models.TextField(blank=True)),
                ('enc_recovery_salt', models.CharField(blank=True, max_length=64)),
                ('has_recovery_words', models.BooleanField(default=False)),
                ('ai_consent', models.CharField(choices=[('full', 'AI on Full Content'), ('metadata', 'AI on Metadata Only'), ('temp_decrypt', 'AI with Temporary Decryption'), ('disabled', 'AI Disabled')], default='full', max_length=20)),
                ('block_type', models.CharField(choices=[('text', 'Text'), ('heading1', 'Heading 1'), ('heading2', 'Heading 2'), ('heading3', 'Heading 3'), ('quote', 'Quote'), ('callout', 'Callout'), ('code', 'Code'), ('divider', 'Divider'), ('todo', 'To-Do'), ('toggle', 'Toggle'), ('kanban', 'Kanban'), ('table', 'Table'), ('spreadsheet', 'Spreadsheet'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('form', 'Form'), ('chart', 'Chart'), ('page_link', 'Page Link'), ('linked_view', 'Linked View'), ('drawing', 'Drawing'), ('mindmap', 'Mind Map'), ('sticky', 'Sticky Note'), ('timer', 'Time Tracker'), ('invoice_block', 'Invoice'), ('bookmark', 'Bookmark'), ('equation', 'Equation'), ('breadcrumb', 'Breadcrumb'), ('column_layout', 'Column Layout'), ('audio', 'Audio'), ('embed', 'Embed')], max_length=50)),
                ('content', models.JSONField(default=dict)),
                ('order', models.FloatField(default=0)),
                ('canvas_x', models.FloatField(blank=True, null=True)),
                ('canvas_y', models.FloatField(blank=True, null=True)),
                ('canvas_w', models.FloatField(blank=True, null=True)),
                ('canvas_h', models.FloatField(blank=True, null=True)),
                ('canvas_z', models.IntegerField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='pages.page')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blocks.block')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['page', 'order'], name='blocks_bloc_page_id_b8a99e_idx'), models.Index(fields=['page', 'block_type'], name='blocks_bloc_page_id_58fbdf_idx'), models.Index(fields=['parent'], name='blocks_bloc_parent__03dbfa_idx'), models.Index(fields=['page', 'is_locked'], name='blocks_bloc_page_id_6ddffc_idx')],
            },
        ),
    ]
