# Generated by Django 6.0.3 on 2026-03-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='canvas_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='block',
            name='doc_visible',
            field=models.BooleanField(default=True),
        ),
    ]
