# Generated by Django 6.0.3 on 2026-03-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0002_block_canvas_visible_block_doc_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_type',
            field=models.CharField(choices=[('text', 'Text'), ('heading1', 'Heading 1'), ('heading2', 'Heading 2'), ('heading3', 'Heading 3'), ('quote', 'Quote'), ('callout', 'Callout'), ('code', 'Code'), ('divider', 'Divider'), ('todo', 'To-Do'), ('toggle', 'Toggle'), ('kanban', 'Kanban'), ('table', 'Table'), ('spreadsheet', 'Spreadsheet'), ('image', 'Image'), ('video', 'Video'), ('file', 'File'), ('form', 'Form'), ('chart', 'Chart'), ('page_link', 'Page Link'), ('linked_view', 'Linked View'), ('drawing', 'Drawing'), ('mindmap', 'Mind Map'), ('sticky', 'Sticky Note'), ('rich', 'Rich Block'), ('timer', 'Time Tracker'), ('invoice_block', 'Invoice'), ('bookmark', 'Bookmark'), ('equation', 'Equation'), ('breadcrumb', 'Breadcrumb'), ('column_layout', 'Column Layout'), ('audio', 'Audio'), ('embed', 'Embed')], max_length=50),
        ),
    ]
