# Generated by Django 6.0.3 on 2026-03-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_add_rich_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='bg_color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
