# Generated by Django 6.0.3 on 2026-04-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0004_add_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_type',
            field=models.CharField(db_index=True, default='paragraph', max_length=50),
        ),
    ]
