# Generated by Django 6.0.3 on 2026-04-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0005_refactor_block_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='text_color',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='block',
            name='bg_color',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
