server {
    listen 80;
    server_name api.spatialscribe.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name api.spatialscribe.com;

    ssl_certificate     /etc/letsencrypt/live/api.spatialscribe.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.spatialscribe.com/privkey.pem;

    client_max_body_size 15M;

    location /static/ {
        alias /var/www/spatialscribe/staticfiles/;
    }

    location /media/ {
        alias /var/www/spatialscribe/media/;
    }

    location / {
        proxy_pass         http://unix:/run/spatialscribe.sock;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
}
