# Generated by Django 6.0.2 on 2026-03-11 18:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blocks', '0001_initial'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('conn_type', models.CharField(choices=[('page_link', 'Page Link'), ('form_sheet', 'Form → Spreadsheet'), ('chart_sheet', 'Chart ← Spreadsheet'), ('timer_proj', 'Timer → Project'), ('inv_client', 'Invoice → Client'), ('date_cal', 'Date → Google Calendar'), ('email_page', 'Email → Page')], max_length=50)),
                ('metadata', models.JSONField(default=dict)),
                ('source_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='blocks.block')),
                ('source_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='pages.page')),
                ('target_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='blocks.block')),
                ('target_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='pages.page')),
            ],
            options={
                'indexes': [models.Index(fields=['conn_type', 'source_page'], name='relations_c_conn_ty_8eedb8_idx'), models.Index(fields=['conn_type', 'target_page'], name='relations_c_conn_ty_fddb0f_idx')],
            },
        ),
    ]
