# Generated by Django 6.0.3 on 2026-03-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='arrow_type',
            field=models.CharField(choices=[('link', 'Visual Link'), ('flow', 'Data Flow')], default='link', max_length=20),
        ),
        migrations.AddField(
            model_name='connection',
            name='direction',
            field=models.CharField(choices=[('directed', 'Directed'), ('undirected', 'Undirected')], default='directed', max_length=20),
        ),
        migrations.AddField(
            model_name='connection',
            name='label',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='connection',
            name='conn_type',
            field=models.CharField(choices=[('page_link', 'Page Link'), ('block_link', 'Block Link'), ('form_sheet', 'Form → Spreadsheet'), ('chart_sheet', 'Chart ← Spreadsheet'), ('timer_proj', 'Timer → Project'), ('inv_client', 'Invoice → Client'), ('date_cal', 'Date → Google Calendar'), ('email_page', 'Email → Page')], max_length=50),
        ),
    ]
