# Generated by Django 6.0.2 on 2026-03-11 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('enc_tier', models.CharField(choices=[('standard', 'Standard'), ('private', 'Private'), ('inherited', 'Inherited'), ('browser', 'Browser Encryption')], default='standard', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('enc_key_blob', models.TextField(blank=True)),
                ('enc_key_salt', models.CharField(blank=True, max_length=64)),
                ('enc_key_hint', models.CharField(blank=True, max_length=255)),
                ('enc_recovery_blob', models.TextField(blank=True)),
                ('enc_recovery_salt', models.CharField(blank=True, max_length=64)),
                ('has_recovery_words', models.BooleanField(default=False)),
                ('ai_consent', models.CharField(choices=[('full', 'AI on Full Content'), ('metadata', 'AI on Metadata Only'), ('temp_decrypt', 'AI with Temporary Decryption'), ('disabled', 'AI Disabled')], default='full', max_length=20)),
                ('name', models.CharField(default='My Space', max_length=255)),
                ('icon', models.CharField(blank=True, default='🏠', max_length=10)),
                ('color', models.CharField(choices=[('white', 'White'), ('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow'), ('blue', 'Blue'), ('purple', 'Purple')], default='white', max_length=20)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('is_personal', models.BooleanField(default=False)),
                ('storage_used_mb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'is_deleted'], name='workspaces__owner_i_941217_idx')],
            },
        ),
    ]
