# Generated by Django 6.0.3 on 2026-04-30 13:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blocks', '0006_add_text_color_to_block'),
        ('pages', '0007_add_page_order'),
        ('properties', '0003_custompagetype_default_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseView',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('view_type', models.CharField(default='table', max_length=30)),
                ('filters', models.JSONField(default=list)),
                ('sorts', models.JSONField(default=list)),
                ('hidden_fields', models.JSONField(default=list)),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='database_view', to='blocks.block')),
                ('custom_page_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='database_views', to='properties.custompagetype')),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('order', models.FloatField(default=0)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='database_rows', to='pages.page')),
                ('database_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='database.databaseview')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('order', models.FloatField(default=0)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_columns', to='properties.propertydefinition')),
                ('database_view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='database.databaseview')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DatabaseCell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('value_text', models.TextField(blank=True, default='')),
                ('value_number', models.FloatField(blank=True, null=True)),
                ('value_date', models.DateTimeField(blank=True, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('value_json', models.JSONField(blank=True, null=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_cells', to='properties.propertydefinition')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='database.databaserow')),
            ],
            options={
                'indexes': [models.Index(fields=['row'], name='database_da_row_id_4c76b7_idx')],
                'unique_together': {('row', 'definition')},
            },
        ),
        migrations.AddIndex(
            model_name='databaseview',
            index=models.Index(fields=['block'], name='database_da_block_i_d13391_idx'),
        ),
        migrations.AddIndex(
            model_name='databaserow',
            index=models.Index(fields=['database_view', 'order'], name='database_da_databas_92f5a2_idx'),
        ),
        migrations.AddIndex(
            model_name='databasecolumn',
            index=models.Index(fields=['database_view', 'order'], name='database_da_databas_da4904_idx'),
        ),
    ]
