# Generated by Django 6.0.2 on 2026-03-11 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sync_version', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('enc_tier', models.CharField(choices=[('standard', 'Standard'), ('private', 'Private'), ('inherited', 'Inherited'), ('browser', 'Browser Encryption')], default='standard', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('enc_key_blob', models.TextField(blank=True)),
                ('enc_key_salt', models.CharField(blank=True, max_length=64)),
                ('enc_key_hint', models.CharField(blank=True, max_length=255)),
                ('enc_recovery_blob', models.TextField(blank=True)),
                ('enc_recovery_salt', models.CharField(blank=True, max_length=64)),
                ('has_recovery_words', models.BooleanField(default=False)),
                ('ai_consent', models.CharField(choices=[('full', 'AI on Full Content'), ('metadata', 'AI on Metadata Only'), ('temp_decrypt', 'AI with Temporary Decryption'), ('disabled', 'AI Disabled')], default='full', max_length=20)),
                ('page_type', models.CharField(choices=[('note', 'Note'), ('secure', 'Secure Page'), ('template', 'Template'), ('client', 'Client'), ('project', 'Project'), ('invoice', 'Invoice'), ('expense', 'Expense'), ('dashboard', 'Dashboard')], default='note', max_length=50)),
                ('view_mode', models.CharField(choices=[('document', 'Document'), ('canvas', 'Canvas')], default='document', max_length=20)),
                ('title', models.CharField(default='Untitled', max_length=500)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('header_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('cover_url', models.URLField(blank=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pages.page')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='workspaces.workspace')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['workspace', 'is_deleted'], name='pages_page_workspa_25a300_idx'), models.Index(fields=['workspace', 'page_type', 'is_deleted'], name='pages_page_workspa_bd6dd0_idx'), models.Index(fields=['parent', 'is_deleted'], name='pages_page_parent__df476c_idx'), models.Index(fields=['workspace', 'is_pinned'], name='pages_page_workspa_968e60_idx')],
            },
        ),
    ]
