# Generated by Django 6.0.2 on 2026-03-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='cover_url',
        ),
        migrations.AlterField(
            model_name='page',
            name='header_pic',
            field=models.ImageField(blank=True, null=True, upload_to='page_headers/'),
        ),
    ]
