# Generated by Django 6.0.3 on 2026-03-15 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_page_cover_url_alter_page_header_pic'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='custom_page_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='properties.custompagetype'),
        ),
    ]
