# Generated by Django 6.0.3 on 2026-03-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_page_custom_page_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='color',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
