# Generated by Django 6.0.3 on 2026-03-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_page_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='color_style',
            field=models.CharField(choices=[('none', 'No color'), ('accent', 'Accent line only'), ('tint', 'Background tint only'), ('both', 'Accent line + background tint')], default='both', max_length=10),
        ),
    ]
