# Generated by Django 6.0.3 on 2026-03-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_color_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='header_pic_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
