# Generated by Django 6.0.3 on 2026-04-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_page_header_pic_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['order', '-updated_at']},
        ),
        migrations.AddField(
            model_name='page',
            name='order',
            field=models.IntegerField(default=0, help_text='Sort order among siblings (lower = first)'),
        ),
    ]
